version: '3'
services:

  database:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:mariadb://database
      -schemas=helpboi
      -table=FLYWAY
      -user=root
      -password=root
      -connectRetries=60
      migrate
    depends_on:
      - database

  api:
    build: ./api
    ports:
      - 8080:8443
    restart: always
    environment:
      DB_HOST: database
    depends_on:
      - database

  client:
    build:
      context: client
      args:
        APP_ENVIRONMENT: 'dev'
    ports:
      - 9091:80
      - 9090:443
      - ${OUTER_WEBPACK_PORT}:${OUTER_WEBPACK_PORT}
    environment:
      CONTAINER_USER:     docker
      CONTAINER_GROUP:    docker
      HOST_UID:           ${HOST_UID} # set in ~/.bashrc
      HOST_GID:           ${HOST_GID} # set in ~/.bashrc
      DEPLOY_ENVIRONMENT:  dev
    restart: always
    depends_on:
      - api
    tty: true
    volumes:
      - ./client/:/var/www/html
