version: '3'
services:

  database:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:mariadb://database
      -schemas=helpboi
      -table=FLYWAY
      -user=root
      -password=root
      -connectRetries=60
      migrate
    depends_on:
      - database

  api:
    build: ./api
    ports:
      - 8080:8080
    restart: always
    environment:
      DB_HOST: database
    depends_on:
      - flyway

  client:
    build: ./client
    ports:
      - 8085:8080
    restart: always
    depends_on:
      - api