micronaut:

  application:
    name: api

  server:
    port: ${PORT:8080}

  ssl:
    enabled: false
    build-self-signed: true

  security:
    basic:
      username: root
      password: root
    enabled: true
    intercept-url-map:
      - pattern: "/health"
        access:
          - isAnonymous()
      - pattern: "/**"
        access:
          - isAuthenticated()

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      documentation:
        paths: classpath:static
        mapping: /**

jpa:
  default:
    packages-to-scan:
      - 'org.helpboi.api.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false

datasources:
  default:
    url: 'jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/helpboi?useLegacyDatetimeCode=false&serverTimezone=UTC'
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver

flyway:
  datasources:
    default:
      table: 'FLYWAY'
      schemas: 'helpboi'
      connect-retries: 60
      locations: classpath:migration